import { pageProps } from "@/utils/types";
import Head from "next/head";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";

export default function Home({ setPageName }: pageProps) {
  const { t } = useTranslation("common");

  useEffect(() => {
    setPageName("Home");
  }, [setPageName]);

  return (
    <>
      <Head>
        <title>BozzWallet</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <h1>{t("homeHeading")}</h1>
        <p>{t("homeTagline")}</p>
      </main>
    </>
  );
}
