import { pageProps } from "@/utils/types/common";
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch } from "react-redux";

export default function Home({ setPageName }: pageProps) {
  const dispatch = useDispatch();

  useEffect(() => {
    setPageName("Home");
  }, []);

  return (
    <>
      <Head>
        <title>BozzWallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hiiii</main>
    </>
  );
}
