import { pageProps } from "@/utils/types";
import Head from "next/head";
import { useEffect, useCallback } from "react";
import { useTranslation } from "react-i18next";

export default function Home({ setPageName, setPageDescription }: pageProps) {
  const namespaces = ["dashboardLayout", "common"];

  const { t } = useTranslation(namespaces);

  const tDashboard = useCallback(
    (key: string) => t(key, { ns: "dashboardLayout" }),
    [t]
  );
  const tCommon = useCallback((key: string) => t(key, { ns: "common" }), [t]);

  useEffect(() => {
    if (setPageName && setPageDescription) {
      // Using dashboardLayout namespace
      setPageName(tDashboard("dashboard"));
      setPageDescription(tDashboard("dashboardDescription"));
    }
  }, [setPageName, setPageDescription, tDashboard]);

  return (
    <>
      <Head>
        <title>BozzWallet</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        {/* Using common namespace */}
        <h1>{tCommon("homeHeading")}</h1>
        <p>{tCommon("homeTagline")}</p>
      </main>
    </>
  );
}
