import { Box, Typography } from "@mui/material";
import Head from "next/head";
import React from "react";
import useIsMobile from "@/hooks/useIsMobile";
import { useTranslation } from "react-i18next";
import { useCallback, useEffect, useState } from "react";
import CustomButton from "@/Components/UI/Buttons";
import {
  AddRounded,
  ArrowOutward as ArrowOutwardIcon,
} from "@mui/icons-material";
import { pageProps } from "@/utils/types";
import { theme } from "@/styles/theme";
import Wallet from "@/Components/Page/Wallet";
import AddWalletModal from "@/Components/UI/AddWalletModal";

const WalletPage = ({
  setPageName,
  setPageDescription,
  setPageAction,
  setPageHeaderSx,
}: pageProps) => {
  const namespaces = ["walletScreen", "common"];
  const isMobile = useIsMobile("md");
  const { t } = useTranslation(namespaces);
  const tDashboard = useCallback(
    (key: string, defaultValue?: string) =>
      t(key, { ns: "walletScreen", defaultValue }),
    [t]
  );

  const [openCreate, setOpenCreate] = useState(false);

  useEffect(() => {
    if (setPageName && setPageDescription) {
      setPageName(tDashboard("walletsTitle"));
      setPageDescription(
        tDashboard(
          "walletsDescription",
          "Manage your cryptocurrency wallet addresses"
        )
      );
    }
  }, [setPageName, setPageDescription, tDashboard]);

  useEffect(() => {
    if (setPageHeaderSx) {
      // Example: You can set custom styles for PageHeader from here
      setPageHeaderSx({
        [theme.breakpoints.down("sm")]: {
          flexDirection: "column",
          justifyContent: "start",
          alignItems: "start",
          gap: 0.5,
        },

        "& .pageAction": {
          [theme.breakpoints.down("sm")]: {
            width: "100%",
          },
        },
      });
    }
    return () => {
      if (setPageHeaderSx) {
        setPageHeaderSx(null);
      }
    };
  }, [setPageHeaderSx]);

  useEffect(() => {
    if (!setPageAction) return;
    setPageAction(
      <>
        <CustomButton
          label={tDashboard("createPaymentLink", "Create payment link")}
          variant="outlined"
          size="medium"
          endIcon={<ArrowOutwardIcon sx={{ fontSize: isMobile ? 14 : 16 }} />}
          onClick={() => {
            // Handle create payment link
          }}
          sx={{
            border: `1px solid ${theme.palette.primary.main}`,
            color: theme.palette.primary.main,
            height: isMobile ? 34 : 40,
            px: isMobile ? 1.5 : 2.5,
            fontSize: isMobile ? 13 : 15,
            "&:hover": {
              border: `1px solid ${theme.palette.primary.main}`,
              color: theme.palette.primary.main,
            },
            "&:disabled": {
              border: `1px solid ${theme.palette.border.main}`,
              color: theme.palette.text.primary,
            },
            [theme.breakpoints.down("sm")]: {
              flex: 1,
            },
          }}
        />
        <CustomButton
          label={tDashboard("addWallet", "Add wallet")}
          variant="primary"
          size="medium"
          endIcon={<AddRounded sx={{ fontSize: isMobile ? 18 : 20 }} />}
          onClick={() => setOpenCreate(true)}
          sx={{
            height: isMobile ? 34 : 40,
            px: isMobile ? 1.5 : 2.5,
            fontSize: isMobile ? 13 : 15,
            [theme.breakpoints.down("sm")]: {
              flex: 1,
            },
          }}
        />
      </>
    );
    return () => setPageAction(null);
  }, [setPageAction, tDashboard, isMobile]);

  const handleAddWallet = (data: {
    walletName: string;
    cryptocurrency: string;
    walletAddress: string;
  }) => {
    console.log("Add wallet:", data);
    // TODO: Implement wallet creation logic
  };

  return (
    <>
      <Head>
        <title>DynoPay - Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Wallet />
        <AddWalletModal
          open={openCreate}
          onClose={() => setOpenCreate(false)}
          onSubmit={handleAddWallet}
        />
      </Box>
    </>
  );
};

export default WalletPage;
