import { Box, Typography } from "@mui/material";
import Head from "next/head";
import React from "react";
import useIsMobile from "@/hooks/useIsMobile";
import { useTranslation } from "react-i18next";
import { useCallback, useEffect, useState } from "react";
import CustomButton from "@/Components/UI/Buttons";
import {
  AddRounded,
  ArrowOutward as ArrowOutwardIcon,
} from "@mui/icons-material";
import { pageProps } from "@/utils/types";
import { theme } from "@/styles/theme";

const WalletPage = ({
  setPageName,
  setPageDescription,
  setPageAction,
}: pageProps) => {
  const namespaces = ["walletScreen", "common"];
  const isMobile = useIsMobile("md");
  const { t } = useTranslation(namespaces);
  const tDashboard = useCallback(
    (key: string, defaultValue?: string) =>
      t(key, { ns: "walletScreen", defaultValue }),
    [t]
  );

  const [openCreate, setOpenCreate] = useState(false);

  useEffect(() => {
    if (setPageName && setPageDescription) {
      setPageName(tDashboard("walletsTitle"));
      setPageDescription(
        tDashboard(
          "walletsDescription",
          "Manage your cryptocurrency wallet addresses"
        )
      );
    }
  }, [setPageName, setPageDescription, tDashboard]);

  useEffect(() => {
    if (!setPageAction) return;
    setPageAction(
      <Box sx={{ display: "flex", gap: 1.5, alignItems: "center" }}>
        <CustomButton
          label={tDashboard("createPaymentLink", "Create payment link")}
          variant="outlined"
          size="medium"
          endIcon={<ArrowOutwardIcon sx={{ fontSize: 16 }} />}
          onClick={() => {
            // Handle create payment link
          }}
          sx={{
            height: 40,
            px: 2.5,
          }}
        />
        <CustomButton
          label={tDashboard("addWallet", "Add wallet")}
          variant="primary"
          size="medium"
          endIcon={<AddRounded />}
          onClick={() => setOpenCreate(true)}
          sx={{ height: 40, px: 2.5 }}
        />
      </Box>
    );
    return () => setPageAction(null);
  }, [setPageAction, tDashboard]);

  return (
    <>
      <Head>
        <title>BozzWallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Typography variant="h6">Wallet</Typography>
      </Box>
    </>
  );
};

export default WalletPage;
