import DataTable from "@/Components/UI/DataTable";
import TextBox from "@/Components/UI/TextBox";
import { WALLET_FETCH, WalletAction } from "@/Redux/Actions/WalletAction";
import { pageProps, rootReducer } from "@/utils/types";
import { Search } from "@mui/icons-material";
import {
  Box,
  Button,
  InputAdornment,
  Typography,
  useTheme,
} from "@mui/material";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

const columns = ["#", "Company Name", "Email", "Amount"];

const Wallet = ({ setPageName }: pageProps) => {
  const theme = useTheme();
  const dispatch = useDispatch();
  const walletState = useSelector((state: rootReducer) => state.walletReducer);
  const [localData, setLocalData] = useState<any[]>([]);
  const [searchValue, setSearchValue] = useState("");

  useEffect(() => {
    setPageName("Wallets");
    dispatch(WalletAction(WALLET_FETCH));
  }, []);

  useEffect(() => {
    if (walletState.walletList.length > 0) {
      const tempArray: any[] = [];
      walletState.walletList.map((x, i) => {
        const tempObj = {
          no: i + 1,
          name: (
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 2,
              }}
            >
              {x.photo ? (
                <img
                  src={x.photo}
                  className="round-img"
                  crossOrigin="anonymous"
                />
              ) : (
                <Box
                  className="round-img"
                  sx={{
                    background: theme.palette.secondary.main + "44",
                    color: "text.secondary",
                    border: "3px solid",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    lineHeight: 0,
                  }}
                >
                  {x.company_name.slice(0, 1)}
                </Box>
              )}
              {x.company_name}
            </Box>
          ),
          hidden: x.company_name,
          email: x.email,
          amount: "$" + x.amount.toFixed(2),
          id: x.wallet_id,
        };
        tempArray.push({ ...tempObj });
      });
      setLocalData(tempArray);
    }
  }, [walletState.walletList]);

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchValue(e.target.value);
  };
  return (
    <>
      <Head>
        <title>BozzWallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ m: 2, mb: 5 }}>
        <Box
          sx={{
            mt: 2,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <TextBox
            customWidth="auto"
            placeholder="Search"
            value={searchValue}
            onChange={handleSearchChange}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <Search />
                </InputAdornment>
              ),
            }}
          />
          <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 1,
                "& p": {
                  fontWeight: 700,
                },
              }}
            >
              <Typography color={"text.secondary"}>Total Balance:</Typography>
              <Typography>${walletState.totalBalance.toFixed(2)}</Typography>
            </Box>
            <Button variant="rounded" color="secondary">
              Withdraw
            </Button>
          </Box>
        </Box>
        <Box>
          <DataTable
            columns={columns}
            data={localData}
            hasAction
            actionText="Action"
            searchValue={searchValue}
            actionColumn={(index) => (
              <Box
                sx={{
                  "& button": {
                    mr: 1,
                  },
                }}
              >
                <Button
                  variant="rounded"
                  disableRipple={false}
                  sx={{ borderRadius: "20px" }}
                  onClick={() => {
                    const id = localData[index].id;
                    alert(id);
                  }}
                >
                  Transactions
                </Button>
              </Box>
            )}
          />
        </Box>
      </Box>
    </>
  );
};

export default Wallet;
